/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import threads.ServerThread;

/**
 *
 * @author Nikola
 */
public class FormServer extends javax.swing.JFrame {

    private ServerThread serverThread;
    /**
     * Creates new form formServer
     */
    public FormServer() {
        initComponents();
        mestopServer.setEnabled(false);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Server = new javax.swing.JMenu();
        mestartServer = new javax.swing.JMenuItem();
        mestopServer = new javax.swing.JMenuItem();
        meLoggedUsers = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Server.setText("Server");

        mestartServer.setText("Start server");
        mestartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mestartServerActionPerformed(evt);
            }
        });
        Server.add(mestartServer);

        mestopServer.setText("Stop server");
        mestopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mestopServerActionPerformed(evt);
            }
        });
        Server.add(mestopServer);

        meLoggedUsers.setText("Logged users");
        Server.add(meLoggedUsers);

        jMenuBar1.add(Server);

        jMenu3.setText("Configuration");

        jMenuItem4.setText("Database configuration");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mestartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mestartServerActionPerformed
        if(serverThread==null || !serverThread.isAlive()){
            try {
                serverThread = new ServerThread();
                serverThread.start();
                
                mestartServer.setEnabled(false);
                mestopServer.setEnabled(true);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mestartServerActionPerformed

    private void mestopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mestopServerActionPerformed
        if(serverThread.getServerSocket()!=null && serverThread.getServerSocket().isBound()){
            try {
                serverThread.getServerSocket().close();
                mestartServer.setEnabled(true);
                mestopServer.setEnabled(false);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mestopServerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Server;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem meLoggedUsers;
    private javax.swing.JMenuItem mestartServer;
    private javax.swing.JMenuItem mestopServer;
    // End of variables declaration//GEN-END:variables
}
